### ISSUE TITLE
Reed Solomon encoder modification for 128 bytes

### ISSUE THREAD

**Issue by jgromes** [fsphil/hadie#2]
Hi,

I came across this project while implementing JPEG picture downlink for FOSSASAT-2. Ultimately I decided not to use SSDV protocol for our downlink (because its 256 byte packet won't fit within our communication protocol packet structure), but I still want to add FEC to the large packets needed to send the picture data.

Would it be possible to modify the RS encoder implemented here for use with 128 data symbols? Judging from some of the details like variable names, I'm guessing the RS encoder in this project is a heavily modified version of http://www.eccpage.com/rs.c simplified only for RS(255, 223) - please let me know if that's not the case.

I don't have much of a background in mathematics or signal processing, but it seems to me there should be some RS code that would be able to handle 128 data symbols, maybe with 16 or 32 FEC bytes? And if that's the case, is it enough to just generate the precomputed arrays (alpha_to, index_of and poly) using the above program?

Thank you very much for any help!

**Comment by fsphil** [comment]
encode_rs_8()'s pad argument is used for handling smaller payloads. Normally the payload is 223 bytes, if you use say 128 bytes you'd pass 95 to pad (223 - 128). You'd then have your 128 bytes plus 32 bytes FEC. There is a similar argument in the RS8 decoder function in the ssdv code at https://github.com/fsphil/ssdv

Just a warning that this repo is very old, there's been several fixes and updates done to ssdv since this.

Smaller SSDV packet sizes are possible, 256 bytes was chosen mostly out of convenience. The overhead is higher but it should work just as well.

**Comment by jgromes** [comment]
That's pretty convenient - thanks! In that case I think it should be possible to reuse your RS encoder as-is (properly licensed, of course) in our on-board code, both for picture downlink as well as for other large packets.

Let's hope we get some nice LEO pictures ;)
